development:
  FB_ID: "327117887762309"
  FB_SECRET: "a25cd31c31d755bdf1053f7caeac77ea"

production:
  FB_ID: "1985042148419643"
  FB_SECRET: "7dfc83c5c9822c5b86f6b26f311cd745"

CLOUDINARY_URL: "cloudinary://475971542781291:2Cvm_-9aseN8QvVI3sSPzmRYliw@dnyotziqv"
GOOGLE_API_SERVER_KEY: "AIzaSyBzLJwXaAHmZxNN6eRqIakuar9MeIYZEoA"
GOOGLE_API_BROWSER_KEY: "AIzaSyAZIpthMHHSftRPk2LYDXzmTU7mrptvW10"

