# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08a58313ab38643b8fabc5479d42fa6848424282c87f452d54cc95d4e7de47020d0a71ef0c318109c13a963432bc5b76d4be3532a691da9d4896be4012c91757

test:
  secret_key_base: e17095c617962f9d4f43121e681954040a26ca3972e325fd696b4b084613e7a6340e74567071d864ce8480df810b575eb75bb9ae7373c0e5c1dda2deab4dfd05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
